In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# Step 1: Import the Excel file
file_path = '/content/AirQualityUCI.xlsx'  # Replace with the actual file path
data = pd.read_excel(file_path)

In [5]:
# Check for the value -200 in any column
columns_with_minus_200 = data.columns[(data == -200).any()].tolist()

if columns_with_minus_200:
    print(f"Columns containing the value -200: {columns_with_minus_200}")
else:
    print("No columns contain the value -200.")

Columns containing the value -200: ['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)', 'T', 'RH', 'AH']

In [6]:
data.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10,18:00:00,2.6,1360.00,150,11.881723,1045.50,166.0,1056.25,113.0,1692.00,1267.50,13.60,48.875001,0.757754
1,2004-03-10,19:00:00,2.0,1292.25,112,9.397165,954.75,103.0,1173.75,92.0,1558.75,972.25,13.30,47.700000,0.725487
2,2004-03-10,20:00:00,2.2,1402.00,88,8.997817,939.25,131.0,1140.00,114.0,1554.50,1074.00,11.90,53.975000,0.750239
3,2004-03-10,21:00:00,2.2,1375.50,80,9.228796,948.25,172.0,1092.00,122.0,1583.75,1203.25,11.00,60.000000,0.786713
4,2004-03-10,22:00:00,1.6,1272.25,51,6.518224,835.50,131.0,1205.00,116.0,1490.00,1110.00,11.15,59.575001,0.788794

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   datetime64[ns]
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   int64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: datetime64[ns](1), float64(12), int64(1), object(1)
memory usage: 1.1+ MB

In [9]:
data.replace(-200, np.nan, inplace=True)

In [10]:
missing_summary = data.isna().sum()
missing_percentage = (missing_summary / len(data)) * 100
missing_df = pd.DataFrame({'Missing Values': missing_summary, 'Percentage': missing_percentage})
print(missing_df)

               Missing Values  Percentage
Date                        0    0.000000
Time                        0    0.000000
CO(GT)                   1683   17.986534
PT08.S1(CO)               366    3.911510
NMHC(GT)                 8443   90.231912
C6H6(GT)                  366    3.911510
PT08.S2(NMHC)             366    3.911510
NOx(GT)                  1639   17.516298
PT08.S3(NOx)              366    3.911510
NO2(GT)                  1642   17.548360
PT08.S4(NO2)              366    3.911510
PT08.S5(O3)               366    3.911510
T                         366    3.911510
RH                        366    3.911510
AH                        366    3.911510

In [11]:
env_cols = ['T', 'RH', 'AH']
data[env_cols] = data[env_cols].interpolate(method='linear', limit_direction='both')

In [12]:
sensor_cols = ['CO(GT)', 'PT08.S1(CO)', 'C6H6(GT)', 'PT08.S2(NMHC)',
               'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)']

for col in sensor_cols:
    if data[col].isna().mean() <= 0.05:
        data[col] = data[col].interpolate(method='linear', limit_direction='both')
    else:
        data[col] = data[col].fillna(data[col].mean())

In [13]:
missing_summary = data.isna().sum()
missing_percentage = (missing_summary / len(data)) * 100
missing_df = pd.DataFrame({'Missing Values': missing_summary, 'Percentage': missing_percentage})
print(missing_df)

               Missing Values  Percentage
Date                        0    0.000000
Time                        0    0.000000
CO(GT)                      0    0.000000
PT08.S1(CO)                 0    0.000000
NMHC(GT)                 8443   90.231912
C6H6(GT)                    0    0.000000
PT08.S2(NMHC)               0    0.000000
NOx(GT)                     0    0.000000
PT08.S3(NOx)                0    0.000000
NO2(GT)                     0    0.000000
PT08.S4(NO2)                0    0.000000
PT08.S5(O3)                 0    0.000000
T                           0    0.000000
RH                          0    0.000000
AH                          0    0.000000

In [14]:
data.drop(columns=["NMHC(GT)"], inplace=True)

In [16]:
data.shape

(9357, 14)

In [18]:
data.head()

,Date,Time,CO(GT),PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10,18:00:00,2.6,1360.00,11.881723,1045.50,166.0,1056.25,113.0,1692.00,1267.50,13.60,48.875001,0.757754
1,2004-03-10,19:00:00,2.0,1292.25,9.397165,954.75,103.0,1173.75,92.0,1558.75,972.25,13.30,47.700000,0.725487
2,2004-03-10,20:00:00,2.2,1402.00,8.997817,939.25,131.0,1140.00,114.0,1554.50,1074.00,11.90,53.975000,0.750239
3,2004-03-10,21:00:00,2.2,1375.50,9.228796,948.25,172.0,1092.00,122.0,1583.75,1203.25,11.00,60.000000,0.786713
4,2004-03-10,22:00:00,1.6,1272.25,6.518224,835.50,131.0,1205.00,116.0,1490.00,1110.00,11.15,59.575001,0.788794

In [20]:
data["Date"] = data["Date"].astype(str)
data["Time"] = data["Time"].astype(str)
data["DateandTime"] = data["Date"] + " " + data["Time"]

data["Datetime"] = pd.to_datetime(data["DateandTime"], format="%d/%m/%Y %H.%M.%S", errors="coerce")

In [21]:
data.head()

,Date,Time,CO(GT),PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,DateandTime,Datetime
0,2004-03-10,18:00:00,2.6,1360.00,11.881723,1045.50,166.0,1056.25,113.0,1692.00,1267.50,13.60,48.875001,0.757754,2004-03-10 18:00:00,NaT
1,2004-03-10,19:00:00,2.0,1292.25,9.397165,954.75,103.0,1173.75,92.0,1558.75,972.25,13.30,47.700000,0.725487,2004-03-10 19:00:00,NaT
2,2004-03-10,20:00:00,2.2,1402.00,8.997817,939.25,131.0,1140.00,114.0,1554.50,1074.00,11.90,53.975000,0.750239,2004-03-10 20:00:00,NaT
3,2004-03-10,21:00:00,2.2,1375.50,9.228796,948.25,172.0,1092.00,122.0,1583.75,1203.25,11.00,60.000000,0.786713,2004-03-10 21:00:00,NaT
4,2004-03-10,22:00:00,1.6,1272.25,6.518224,835.50,131.0,1205.00,116.0,1490.00,1110.00,11.15,59.575001,0.788794,2004-03-10 22:00:00,NaT

In [22]:
data = data.drop(columns=["Datetime"])
data.head()

,Date,Time,CO(GT),PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,DateandTime
0,2004-03-10,18:00:00,2.6,1360.00,11.881723,1045.50,166.0,1056.25,113.0,1692.00,1267.50,13.60,48.875001,0.757754,2004-03-10 18:00:00
1,2004-03-10,19:00:00,2.0,1292.25,9.397165,954.75,103.0,1173.75,92.0,1558.75,972.25,13.30,47.700000,0.725487,2004-03-10 19:00:00
2,2004-03-10,20:00:00,2.2,1402.00,8.997817,939.25,131.0,1140.00,114.0,1554.50,1074.00,11.90,53.975000,0.750239,2004-03-10 20:00:00
3,2004-03-10,21:00:00,2.2,1375.50,9.228796,948.25,172.0,1092.00,122.0,1583.75,1203.25,11.00,60.000000,0.786713,2004-03-10 21:00:00
4,2004-03-10,22:00:00,1.6,1272.25,6.518224,835.50,131.0,1205.00,116.0,1490.00,1110.00,11.15,59.575001,0.788794,2004-03-10 22:00:00

In [23]:
data.to_csv('cleaned_data.csv', index=False)

In [24]:
data.to_excel('cleaned_data.xlsx', index=False)

In [30]:
columns_with_minus_200 = data.columns[(data == -200).any()].tolist()

if columns_with_minus_200:
    print(f"Columns containing the value -200: {columns_with_minus_200}")
else:
    print("No columns contain the value -200.")

No columns contain the value -200.

In [31]:
columns_with_nan = data.columns[(data == np.nan).any()].tolist()

if columns_with_nan:
    print(f"Columns containing the value nan: {columns_with_nan}")
else:
    print("No columns contain the value nan.")

No columns contain the value nan.